import { XYPosition } from 'react-flow-renderer';

// this is a temporary class - eventually we'll need events too I assume
class DialogueNode {
	private static last_id: number = 0;
	id: string;
	private _character_name: string = "";
	get character_name() {
		return this._character_name;
	}
	set character_name(value: string) {
		this._character_name = value;
		this._set_data();
	}

	_dialogue: string = "";
	get dialogue() {
		return this._dialogue;
	}
	set dialogue(value: string) {
		this._dialogue = value;
		this._set_data();
	}

	type: string = "default";

	// data is generated by the character name and dialogue option
	data: object = {};

	// position is based on the x and y variables
	// this could probably be surfaced as an object instead of this read only thing
	// but who's to say
	position: XYPosition;

	// ctor
	constructor(character_name: string, dialogue: string) {
		this.character_name = character_name;
		this.dialogue = dialogue;
		this.id = (DialogueNode.last_id++).toString();
		this.position = { x: 250, y: 250 };
		this._set_data();
	}

	private _set_data() {
		this.data = {
			label: (
				<>
				<h2>{this.character_name}</h2>
				<p>{this.dialogue}</p>
				</>
			)
		};
	}
}

export default DialogueNode;