import React from 'react'
import { Position, XYPosition } from 'react-flow-renderer'

// this is a temporary class - eventually we'll need events too I assume
class DialogueNode {
	private static last_id: number = 1

	id: string

	sourcePosition: Position

	targetPosition: Position

	private _character_name: string = ''

	get character_name() {
		return this._character_name
	}

	set character_name(value: string) {
		this._character_name = value
		this._set_data()
	}

	_dialogue: string = ''

	get dialogue() {
		return this._dialogue
	}

	set dialogue(value: string) {
		this._dialogue = value
		this._set_data()
	}

	type: string = 'default'

	// data is generated by the character name and dialogue option
	data: object = {}

	// position is based on the x and y variables
	// this could probably be surfaced as an object instead of this read only thing
	// but who's to say
	position: XYPosition

	// ctor
	constructor(
		character_name: string,
		dialogue: string,
		x: number,
		y: number,
		TB?: boolean
	) {
		this.character_name = character_name
		this.dialogue = dialogue
		this.id = (DialogueNode.last_id++).toString()
		this.position = { x, y }
		if (TB) {
			this.sourcePosition = Position.Bottom
			this.targetPosition = Position.Top
		} else {
			this.sourcePosition = Position.Right
			this.targetPosition = Position.Left
		}
		this._set_data()
	}

	edit(event: any) {
		console.log(this)
		console.log(event)
	}

	private _set_data() {
		this.data = {
			label: (
				<>
					<h2>{this.character_name}</h2>
					<p>{this.dialogue}</p>
					<button onClick={this.edit}>Edit</button>
				</>
			),
		}
	}
}

export default DialogueNode
